# Generated by Django 2.0.6 on 2018-06-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='table_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='singleorder',
            name='count',
            field=models.IntegerField(),
        ),
    ]
