# Generated by Django 2.0.6 on 2018-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180612_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=3)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='singleorder',
            name='status',
            field=models.CharField(choices=[('ongoing', '未送出'), ('submitted', '已送出'), ('payed', '已付款'), ('done', '已完成')], default='未送出', max_length=4),
        ),
    ]
