# Generated by Django 2.0.6 on 2018-06-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180612_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleorder',
            name='status',
            field=models.CharField(choices=[('ongoing', '未送出'), ('submitted', '已送出'), ('payed', '已付款'), ('done', '已完成')], default='ongoing', max_length=4),
        ),
    ]
