# Generated by Django 2.0.6 on 2018-06-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180612_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='table_id',
            new_name='table',
        ),
        migrations.AlterField(
            model_name='singleorder',
            name='status',
            field=models.CharField(choices=[('unsent', '未下單'), ('unconfirmed', '服務生未確認'), ('confirmed', '服務生已確認'), ('payed', '已付款')], default='ongoing', max_length=4),
        ),
    ]
