# Generated by Django 2.0.6 on 2018-06-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180613_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='singleorder',
            name='status',
            field=models.CharField(choices=[('unsent', '未下單'), ('unconfirmed', '服務生未確認'), ('confirmed', '服務生已確認'), ('payed', '已付款')], default='unsent', max_length=4),
        ),
    ]
